- name: nginx_install_and_config
  tags: nginx
  block:

  - name: Ensure EPEL is disabled
    yum_repository:
      name: epel
      state: absent
    when: ansible_distribution in ['CentOS', 'RedHat']

  - name: Add Nginx repository
    copy:
      content: "{{ nginx_repo_content }}"
      dest: /etc/yum.repos.d/nginx.repo
      owner: root
      group: root
      mode: '0644'

  - name: Import GPG key
    rpm_key:
      key: https://nginx.org/keys/nginx_signing.key
      state: present

  - name: Install Nginx
    package:
      name: nginx
      state: latest
    notify:
      - enable nginx
      - start nginx

  - name: Create Nginx config directory
    file:
      path: /etc/nginx/conf.d
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Deploy main Nginx configuration
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
    notify:
      - reload nginx

  - name: Deploy default server configuration
    template:
      src: nginx.conf.j2
      dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
      owner: root
      group: root
      mode: '0644'
    with_items: "{{ list }}"
    notify:
      - reload nginx

  - name: Ensure web root directory exists
    file:
      path: "{{ web_root }}"
      state: directory
      mode: '0755'
      owner: "{{ nginx_user }}"
      group: "{{ nginx_user }}"

  - name: Ensure service is running
    service:
      name: nginx
      state: started
      enabled: yes

