- name: Apply common configuration
  hosts: myhosts
  become: yes
  roles:
    - common

- name: Install Docker
  hosts: myhosts
  become: yes
  roles:
    - docker

- name: Install Nginx
  hosts: myhosts
  become: yes
  roles:
    - nginx